### PR TITLE
Update mintty to 2.3.4

### PR DESCRIPTION
**Pull request by paladox**
This updates minty to 2.3.4.

See changelog at https://github.com/mintty/mintty/releases please.

But accoriding to the notes the main changes are

Highlights to previous major version (details see 2.3.2):
•Font setup and configuration improvements.
•Colour schemes / Theme files.
•GUI configuration of wav file for terminal beep.
•Startup error handling improvements.

### CODE REVIEW

**Comment by dscho** [comment]
Have you actually tried to *build* the package using `makepkg`?

**Comment by paladox** [comment]
No.

**Comment by elieux** [comment]
@dscho, if you're referring to build failures with new msys2-devel, mintty/mintty#532 could be useful.

**Comment by dscho** [comment]
@elieux no, I was not even trying to build here, but suspected that the patches we carry in Git for Windows' fork of MSYS2-package would not even apply cleanly. And I wanted to make sure that my suspicion was correct before saying anything else.

**Comment by dscho** [comment]
> > Have you actually tried to build the package using makepkg?
> 
> Nope.

That is bad. You basically contributed changes that you did not even verify are good. Please do not do that, it just costs both of us unnecessary time.

**Pull request closed without merging**
