### PR TITLE
Prepare for building libgcrypt in Git for Windows

### PR DESCRIPTION
**Pull request by dscho**
The most recent upgrade to GNU Privacy Guard v2.2.8 failed, for now, most likely due to the i686 version of libgcrypt being too old (the MSYS2 project no longer builds i686 versions of its MSYS2 packages).

Let's build libgcrypt ourselves in Git for Windows, and upgrade it to v1.9.3 at the same time.

### CODE REVIEW

**Review by rimrul — APPROVED** [review]
looks exactly like the 1.9.2 changes in MSYS2/MSYS2-packages. Should work as expected.

**Comment by dscho** [comment]
> 
> 
> looks exactly like the 1.9.2 changes in MSYS2/MSYS2-packages. Should work as expected.

Plus, the build succeeded ;-)

**Comment by dscho** [comment]
The Azure Pipeline is building libgcrypt here: https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=78931&view=results

**Comment by dscho** [comment]
Unfortunately, I had to edit the Azure Pipeline definition to force `rebaseall` for `libgcrypt`, and then to restart the run: https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=78932&view=results

**Comment by dscho** [comment]
Looks like the i686 version has problems validating:

```
[...]
PASS: version.exe
t-secmem: line 184: gcry_control ((GCRYCTL_INIT_SECMEM, pool_size, 0)) failed: General error
FAIL: t-secmem.exe
PASS: mpitests.exe
t-sexp: line 1321: gcry_control ((GCRYCTL_INIT_SECMEM, 16384, 0)) failed: General error
[...]
```

**Comment by rimrul** [comment]
Do we have an up-to-date `libgpg-error` for i686?

**Comment by dscho** [comment]
> 
> 
> Do we have an up-to-date `libgpg-error` for i686?
> 
> The MSYS2 `PKGBUILD` has version 1.42, ours only 1.32, so it's probably the same situation as with `libgcrypt`

Turns out that the problem was somewhere completely different. Believe it or not, the `t-secmem`/`t-sexp` problem is fixed by https://github.com/git-for-windows/MSYS2-packages/pull/43/commits/69835494e36c1f2e782d055cd60813e80229a9ae.

**Pull request merged**
