### PR TITLE
Upgrade openssh to v9.1

### PR DESCRIPTION
**Pull request by dscho**
This is a work-in-progress, mainly because I want to upgrade libfido2, too, in order to get `ssh-keygen -t ecdsa-sk` to use Windows Hello, but in my current attempts to build it, things break like this:

```console
$ ssh-keygen.exe -v -v -v -v -v -v -t ecdsa-sk
Generating public/private ecdsa-sk key pair.
You may need to touch your authenticator to authorize key generation.
debug3: start_helper: started pid=53312
debug3: ssh_msg_send: type 5
debug3: ssh_msg_recv entering
debug1: start_helper: starting /usr/lib/ssh/ssh-sk-helper
ssh_msg_recv: read header: Software caused connection abort
client_converse: receive: unexpected internal error
debug3: reap_helper: pid=53312
reap_helper: helper exited with non-zero exit status
Key enrollment failed: unexpected internal error
```

This addresses https://github.com/git-for-windows/git/issues/4051

### CODE REVIEW

**Comment by dscho** [comment]
I've decided to let the libfido2 upgrade slide for a while, as I suspect it to be quite a bit involved due to the segmentation fault (the first time I tried to get libfido2 to build and work properly, it took a couple of days to get it right, that's an amount of time I cannot spare right now).

**Review by rimrul — APPROVED** [review]

**Comment by dscho** [comment]
Now off to the races: [build `libcbor` first](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=108558&view=results).

**Comment by dscho** [comment]
And now [libfido2](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=108562&view=results).

**Comment by dscho** [comment]
> And now [libfido2](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=108562&view=results).

Which failed because of a missing public key. I edited the Azure Pipeline definition and started [another build](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=108564&view=results).

**Comment by dscho** [comment]
And now, finally, [let's build `openssh`](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=108567&view=results).

**Comment by dscho** [comment]
It finally built all right!

**Pull request merged**
