### PR TITLE
Revert "msys2-runtime-devel: bundle .pdb instead of .dbg files"

### PR DESCRIPTION
**Pull request by dakotahawkins**
Fixes git-for-windows/git#356

This reverts commit c8e710e5525f29abaf8cd18d5e8851133faf9035.

Signed-off-by: Dakota Hawkins <dakotahawkins@gmail.com>

Supersedes #26

### CODE REVIEW

**Comment by dscho** [comment]
Thank you for your patience, and for completing this!

**Comment by dakotahawkins** [comment]
@dscho Thanks for getting it in! I'm super excited for this to be fixed!

**Comment by shiftkey** [comment]
@gilly3 pre-release packages are available [here](https://wingit.blob.core.windows.net/files/index.html) and should be tracking `master` on `git-for-windows/git`.

**Comment by dscho** [comment]
Indeed, the prereleases are the best way to get new features and bug fixes early, and to ensure that they work for you.

@gilly3 please test.

As to the next release: http://tinyurl.com/gitCal projects the next Git release to be v2.19.0 on or around September 9th, 2018. I would imagine that Git for Windows v2.19.0 will be released soon thereafter, unless we hit road blocks.

**Pull request merged**
