### PR TITLE
Git for windows mirrorlist

### PR DESCRIPTION
**Pull request by sschuberth**
We still need to agree on whether distinguish between MinGW and MSYS2 packages in the repo / URL.

Also, for some reason I suddenly cannot compile pacman anymore in order to create the binary packages for this PR. I'm getting:

In file included from pacsort.c:28:0:
util-common.h:1:1: error: expected identifier or ‘(’ before ‘.’ token
 ../common/util-common.h
 ^

and a ton of

pacsort.c: In function ‘buffer_new’:
pacsort.c:77:25: error: dereferencing pointer to incomplete type
  buf = calloc(1, sizeof(*buf));
                         ^
I still need to figure out what's going on.

### CODE REVIEW

**Comment by dscho** [comment]
> In file included from pacsort.c:28:0:
> util-common.h:1:1: error: expected identifier or ‘(’ before ‘.’ token
> ../common/util-common.h

Funny, I had exactly the same issue just now.

It looks as if some part of the build wants to link `../common/util-common.[ch]` *symbolically* into `src/pacman/src/util/` and fails to do that.

Since the `PKGBUILD` lists the source as a Git repository, my hunch is that some recent update of MSys2 Git handles symbolic links incorrectly by writing out the paths directly (this is what Git for Windows does, but MSys2 is supposed to *know* about symbolic links).

Upon further inspection, it seems as if the `src/pacman/.git/config` contains `core.symlinks = false` which is *most likely* the culprit. I just tested, and yes, if I call `git init` with the *MSys2* Git in an empty directory, `core.symlinks` *is* set to `false`.

The really bad part is that it seems as if the  `$HOME/.gitconfig` cannot override that behavior :-(

**Comment by dscho** [comment]
BTW I suspect that putting something like

```bash
test "../common/util-common.h" = "$(cat src/util/util-common.h)" &&
cp src/common/util-common.[ch] src/util/
```

*just* before the `make -j1` line in the `PKGBUILD`'s `build` function should work around it.

**Comment by dscho** [comment]
In the meantime, I merged with upstream (with the idea that it is easier to stay up-to-date if we update frequently) and fixed the `util-common.h` issue in 7a7b0ed.

**Comment by dscho** [comment]
Unfortunately, my merge with upstream results in merge conflicts for this Pull Request. @sschuberth I am sorry! If you do not get around to rebase this branch, I can do that tomorrow.

**Comment by sschuberth** [comment]
Closing this due to [these findings](https://github.com/git-for-windows/git/issues/30#issuecomment-78441124) and the discussion in the following comments in that issue.

**Pull request closed without merging**
