### PR TITLE
Updated libcbor and libfido2

### PR DESCRIPTION
**Pull request by tavrez**
The next version of OpenSSH(version 8.4p1) has new features which are only available in libfido v1.5.0

### CODE REVIEW

**Comment by dscho** [comment]
Git for Windows' components are actually upgraded as part of two Pipelines (that I trigger manually, specifying which package needs to be upgraded). Meaning: the commit is created as part of that Pipeline, and only pushed once the package built successfully and was also successfully uploaded to the Pacman repository.

I triggered the `libcbor` upgrade here: https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=63157&view=results (and plan on triggering the `libfido2` upgrade after that succeeded).

**Comment by dscho** [comment]
Ooops. I totally missed that you had build fixes in this PR. Will merge, then bump down `pkgrel` to 0, and re-trigger the Pipeline.

**Comment by dscho** [comment]
`libcbor` build: https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=63158&view=results

**Comment by dscho** [comment]
`libfido2` build: https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=63159&view=results

**Comment by dscho** [comment]
Both builds succeeded. Thanks @tavrez!

**Comment by tavrez** [comment]
Thanks for merging. Wanted to add a note: I saw you upgraded OpenSSH to v8.4p1, have you used these new packages to build it? If no, it will lose some of it's FIDO functionalities, I suggest you rebuild the OpenSSH with these versions.

**Comment by dscho** [comment]
The upgraded libraries _should_ have been used to build the new OpenSSH. Maybe you can determine via a study of the logs at https://dev.azure.com/git-for-windows/git/_build/results?buildId=63298&view=results whether the build worked as you wanted?

**Comment by tavrez** [comment]
Yes, thanks for the information, it seems fine.

**Pull request merged**
