### PR TITLE
gnupg: update to v2.3.8

### PR DESCRIPTION
**Pull request by dscho**
The release notes for GNU Privacy Guard 2.3.8 are [here](https://lists.gnupg.org/pipermail/gnupg-announce/2022q4/000476.html).

This closes https://github.com/git-for-windows/track-website-changes/issues/7

### CODE REVIEW

**Comment by rimrul** [comment]
We're using https://github.com/git-for-windows/track-website-changes again?

**Comment by rimrul** [comment]
I guess it's time to brush the dust off https://github.com/git-for-windows/track-website-changes/pull/5

**Comment by rimrul** [comment]
This is giving me flashbacks to https://github.com/git-for-windows/git/issues/3267.
Didn't we specifically  backport `gnupg/0003-dirmngr-Fix-build-with-no-LDAP-support.patch` for 2.2.28 from upstream and then drop it from 2.2.29 because it was included in the upstream version? Why is it back? Did they only include it in the 2.2 line?

**Comment by dscho** [comment]
> We're using [track-website-changes](https://github.com/git-for-windows/track-website-changes) again?

I did not find any way to do this with RSS feeds. The [gitweb interface used by GNU Privacy Guard](https://git.gnupg.org/cgi-bin/gitweb.cgi) does not provide us with tag updates 😞

> Didn't we specifically backport `gnupg/0003-dirmngr-Fix-build-with-no-LDAP-support.patch` for 2.2.28 from upstream and then drop it from 2.2.29 because it was included in the upstream version?

Oh wow, I had forgotten all about _that_...

> Why is it back?

It's not exactly back. It's _another_ issue... compare [the old patch](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commitdiff;h=c8b2162c0e7eb42b74811b7ed225fa0f56be4083) to [the new patch](https://github.com/git-for-windows/MSYS2-packages/blob/55930e6569d479b5fa91a739114fbd45c10db897/gnupg/0003-dirmngr-Fix-build-with-no-LDAP-support.patch). We're still not building with LDAP support (at least as far as I know) and I think we therefore need this patch lest we run into link errors where an LDAP-only function is not found (and shouldn't be, really).

**Comment by dscho** [comment]
FWIW my biggest concern is the jump to v2.3.x, so close after Git for Windows v2.39.0 was released. A v2.39.1 may be needed before the holidays and I do not necessarily want to risk including a GNU Privacy Guard version in that release which increases the risk of introducing new regressions... @rimrul what's your take on this? How stable is gnupg v2.3.x?

**Comment by rimrul** [comment]
> How stable is gnupg v2.3.x?

Honestly, I don't know. I took a look at https://gnupg.org/ and they say 

> The current version of GnuPG is 2.2.40. 

Their downloads page on the other hand lists 2.3.8 without any special remarks and calls 2.2.40 an LTS release. I've also looked at some linux distros and most of them are still on 2.2.x, but some are on 2.3.8. That is most likely selection bias, though.

> FWIW my biggest concern is the jump to v2.3.x, so close after Git for Windows v2.39.0 was released. A v2.39.1 may be needed before the holidays and I do not necessarily want to risk including a GNU Privacy Guard version in that release which increases the risk of introducing new regressions... @rimrul what's your take on this? 

We could also hold back on merging this PR until after the holidays. It's not like we urgently need this.

**Comment by dscho** [comment]
I agree, we can easily wait until next year.

There was _one_ report that `pinentry` is no longer in the foreground (git-for-windows/git#3789). But that contributor seems to be less eager to address this than I seemed to be, so I'm inclined to scale back my eagerness accordingly.

**Comment by dscho** [comment]
Let's stay with the LTS track for now, i.e. continue with https://github.com/git-for-windows/MSYS2-packages/pull/98

**Pull request closed without merging**
