### PR TITLE
Added GNU Stow

### PR DESCRIPTION
**Pull request by tavrez**
Great package for handling dotfiles https://dotfiles.github.io/

### CODE REVIEW

**Comment by dscho** [comment]
Great idea! However, why limit this to Git for Windows' SDK? I'd like to suggest to re-open this PR at https://github.com/msys2/MSYS2-packages/pulls, so that all MSYS2 users (not only the Git for Windows users, which are "implicit MSYS2 users") get the benefit.

**Comment by tavrez** [comment]
Good idea, sent!

**Comment by tavrez** [comment]
A question, can it work? I mean, symlink in bash in Windows. I can't create symlinks with `ln` command in Windows

**Comment by dscho** [comment]
In the default mode, the MSYS2 runtime indeed does not create symlinks on Windows 10. The reason: it requires a _recent_ Windows 10, _and_ it needs to be run in Developer Mode (or by an administrator) to have permissions to create symlinks.

You _can_ tell the MSYS2 runtime to create symlinks via `ln -s`, though: set the environment variable `MSYS` to contain `winsymlinks:nativestrict` (see https://cygwin.com/cygwin-ug-net/using-cygwinenv.html, which talks about the environment variable `CYGWIN` which was renamed to `MSYS` in MSYS2 to avoid conflicts).

**Pull request closed without merging**
