### PR TITLE
Update gnupg

### PR DESCRIPTION
**Pull request by ameer1234567890**
gnupg is currently at 1.4.22 which is old considering that we now have 2.2.9 at upstream. gpg 1.4.22 also does not have the gpg-agent which is useful for many developers on Windows.

Signed-off-by: Ameer Dawood <ameer1234567890@gmail.com>

### CODE REVIEW

**Comment by ameer1234567890** [comment]
Since these are cherry-picked commits from upstream, do I need to edit them and add the Signed-off line?

**Comment by dscho** [comment]
We do not build those packages ourselves, but consume upstream's, as you can see here: https://github.com/git-for-windows/git-sdk-64/tree/8b292ea23c136ef7a94053d15d2ff884dcdea456/var/lib/pacman/local/gnupg-2.2.9-1

So I am not sure that this PR is even needed.

**Comment by ameer1234567890** [comment]
Then why is gpg at 1.4.22 in the releases while upstream is at 2.2.9 ?

**Comment by dscho** [comment]
> Then why is gpg at 1.4.22 in the releases while upstream is at 2.2.9 ?

Because there had not been any official release of Git for Windows since MSYS2 updated their GPG.

You can, however, see test the just-released Git for Windows v2.19.0-rc0: https://github.com/git-for-windows/git/releases/tag/v2.19.0-rc0.windows.1

**Pull request closed without merging**
