### PR TITLE
Git sdk installer

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by sschuberth** [comment]
An installer with these changes is available for testing at https://dl.dropboxusercontent.com/u/6413030/git-sdk-i686-20150303.exe.

**Comment by nalla** [comment]
Installer looks good. Worked out of the box. Could clone and compile git.

**Comment by sschuberth** [comment]
Thanks for checking. So I'll probably start setting up some CI around it.

**Comment by t-b** [comment]
@sschuberth The installer works as I can compile git and all tests pass. I'm using https://github.com/dscho/git/tree/update-to-2.3.0 as my tests.

**Comment by dscho** [comment]
Awesome work @sschuberth!

**Comment by t-b** [comment]
One thing I forgot to mention. My antivirus (Avira Pro, sorry I have to use one) always complains about the file ldh.exe containing some kind of trojan. I'll try to that sorted out on the avira side of things.

**Comment by t-b** [comment]
And [here](https://analysis.avira.com/en/status?uniqueid=WHIP8LbZHv0qTRhLhqHOXBGxhKqQyHpD&incidentid=1832598) is the reply from avira. With the next update `ldh.exe` should not be considered malicious anymore.

**Comment by sschuberth** [comment]
Wow, that was quite a quick response from their side, no? Thanks @t-b!

**Pull request merged**
